додано модуль фс
mavka-ukr/mavka pull request #44
Opened 2023-04-20 19:30 UTC by denkisil

перший варіант додавання модулю для роботи з файлової системи.

2023-04-20 19:40 UTC, ghost commented
апостроф треба змінити на ʼ замість '

2023-04-20 21:02 UTC, ghost commented
@denkisil додай в ревʼювери мене, @ArtemiiKravchuk та @dkostmii

2023-04-21 11:16 UTC, ghost commented
@ArtemiiKravchuk @dkostmii що скажете на рахунок цього PR?

2023-04-21 11:30 UTC, dkostmii commented
> @ArtemiiKravchuk @dkostmii що скажете на рахунок цього PR?

+, FS цілком і повністю заслуговує місце у вбудованих модулях

2023-04-21 11:31 UTC, dkostmii commented
Але у разі чого, у веб-версії потрібен механізм, аби сповістити, що цей модуль не можна використати

2023-04-21 11:44 UTC, dkostmii requested changes
Потрібно виправити деякі моменти: як-от замінити порівняння `==` на строге `===` та відображати шлях файлу чи теки при помилках.

Окрім цих моментів, решта коду виглядає добре

2023-04-21 11:44 UTC, dkostmii commented on src/startup-modules/фс.м
> +			return mavka.fall(context, mavka.makeText('тека вже існує'));
Гарним тоном буде друкувати шлях до теки у помилках

2023-04-21 11:44 UTC, dkostmii commented on src/startup-modules/фс.м
> +		if (!(typeof path == 'string'))
Використовувати строге порівняння `===` замість звичайного `==`

2023-04-21 11:47 UTC, dkostmii commented on src/startup-modules/фс.м
> +		if (!(typeof path == 'string'))
Ну і вираз `!(typeof path === 'string')` можна упростити до `typeof path !== 'string'`

2023-04-21 12:00 UTC, ArtemiiKravchuk approved these changes
Як на мене, тут все добре. Погоджуючись з @dkostmii, можна спробувати додати більш зрозуміле повідомлення помилки при запуску модуля з веб-версії.
Також може перейменувати модуль з `фс` до `ФС`, як модуль `М`, якось зрозуміліше стане?
Ну а ще я б додав типизацію, де її немає, то вже таке...

2023-04-21 15:30 UTC, ArtemiiKravchuk commented on src/startup-modules/фс.м
> +			return mavka.fall(context, mavka.makeText(`тека ${path}  вже існує`));
Два пробіли тут спеціально чи випадково?

2023-04-21 15:48 UTC, denkisil commented on src/startup-modules/фс.м
> +			return mavka.fall(context, mavka.makeText(`тека ${path}  вже існує`));
випадково

2023-04-21 16:24 UTC, denkisil commented
@dkostmii @ArtemiiKravchuk @kohutd  наче все виправив

2023-04-21 19:30 UTC, dkostmii approved these changes
Ок, підтверджую

2023-04-21 19:30 UTC, dkostmii commented
Можна мерджити

2023-04-21 22:21 UTC, merged